// angular-app/src/app/components/drag-drop/plato-drop-zone/plato-drop-zone.component.ts
import { Component, Input, Output, EventEmitter, ElementRef, ViewChild, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponenteServido } from '../../../models/decision.model';
import { Ingrediente } from '../../../services/game-data.service';
import { DragDropService } from '../../../services/drag-drop.service';

export interface IngredienteEnPlato {
  ingrediente: Ingrediente;
  cantidad: number;
  unidad: string;
  x: number;
  y: number;
  size: number;
  rotation: number;
}

interface DropPoint {
  x: number;
  y: number;
}

@Component({
  selector: 'app-plato-drop-zone',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './plato-drop-zone.component.html',
  styleUrls: ['./plato-drop-zone.component.scss']
})
export class PlatoDropZoneComponent implements OnChanges {
  @Input() ingredientesEnPlato: IngredienteEnPlato[] = [];
  @Input() personajeActual: any = null; // Personaje actual para mostrar su imagen
  @Output() ingredienteAgregado = new EventEmitter<IngredienteEnPlato>();
  @Output() ingredienteEliminado = new EventEmitter<number>();
  @Output() platoServido = new EventEmitter<ComponenteServido[]>();
  @Output() limpiarSolicitado = new EventEmitter<void>();

  @ViewChild('plateArea') plateAreaRef?: ElementRef<HTMLDivElement>;
  @ViewChild('plateImage') plateImageRef?: ElementRef<HTMLImageElement>;

  mesaImagen = 'assets/images/ingredientes/mesa.png';
  mantelImagen = 'assets/images/ingredientes/mantel.png';
  platoImagen = 'assets/images/ingredientes/plato.png';
  isDragOver = false;

  get personajeImagen(): string | null {
    if (this.personajeActual?.imagen) {
      return `assets/images/ingredientes/${this.personajeActual.imagen}`;
    }
    // Por ahora usar el niño por defecto
    return 'assets/images/ingredientes/niño.png';
  }

  private readonly tamanosVisuales: Record<string, number> = {
    'Pollo': 50,
    'Bistecs': 55,
    'Huevo': 45,
    'Tocineta': 45,
    'Arroz': 45,
    'Plátano': 48,
    'Papa': 45,
    'Pasta': 48,
    'Granos': 45,
    'Pan': 50,
    'Tomate': 38,
    'Lechuga': 42,
    'Brócoli': 45,
    'Zanahoria': 48,
    'Pepino': 40,
    'Naranja': 45,
    'Lechosa': 50,
    'Cambur': 45,
    'Fresa': 40,
    'Piña': 55
  };

  constructor(private dragDropService: DragDropService) {}

  ngOnChanges(changes: SimpleChanges): void {
    // Este método se llama cuando cambian los @Input()
    // Angular detectará automáticamente los cambios en ingredientesEnPlato
  }

  trackByIndex(index: number): number {
    return index;
  }

  handleDragOver(event: DragEvent): void {
    event.preventDefault();
    if (event.dataTransfer) {
      event.dataTransfer.dropEffect = 'copy';
    }
  }

  handleDragEnter(event: DragEvent): void {
    event.preventDefault();
    this.isDragOver = true;
    const plateArea = this.plateAreaRef?.nativeElement;
    const plateContainer = plateArea?.closest('.plate-container') as HTMLElement;
    if (plateArea) {
      plateArea.classList.add('dragging-active');
    }
    if (plateContainer) {
      plateContainer.classList.add('dragging-active');
    }
  }

  handleDragLeave(event: DragEvent): void {
    event.preventDefault();
    this.isDragOver = false;
    const plateArea = this.plateAreaRef?.nativeElement;
    const plateContainer = plateArea?.closest('.plate-container') as HTMLElement;
    if (plateArea) {
      plateArea.classList.remove('dragging-active');
    }
    if (plateContainer) {
      plateContainer.classList.remove('dragging-active');
    }
  }

  handleDrop(event: DragEvent): void {
    event.preventDefault();
    event.stopPropagation();
    this.isDragOver = false;
    const plateArea = this.plateAreaRef?.nativeElement;
    const plateContainer = plateArea?.closest('.plate-container') as HTMLElement;
    if (plateArea) {
      plateArea.classList.remove('dragging-active');
    }
    if (plateContainer) {
      plateContainer.classList.remove('dragging-active');
    }

    const ingrediente = this.dragDropService.getDraggedIngredient();
    if (!ingrediente) {
      console.warn('No hay ingrediente en el servicio de drag-drop');
      return;
    }

    const pointer = { x: event.clientX, y: event.clientY };
    const posicionManual = this.calcularPosicionManual(pointer, ingrediente);

    if (posicionManual) {
      this.tryAgregarIngrediente(ingrediente, null, true, posicionManual);
    } else {
      console.warn('No se pudo calcular la posición manual');
    }

    this.dragDropService.clear();
  }

  tryAgregarIngrediente(
    ingrediente: Ingrediente,
    dropPoint?: DropPoint | null,
    preferDropPoint = false,
    overridePosition?: { x: number; y: number }
  ): void {
    const nuevo = this.crearIngredienteEnPlato(
      ingrediente,
      dropPoint || undefined,
      preferDropPoint,
      overridePosition
    );
    if (nuevo) {
      this.ingredienteAgregado.emit(nuevo);
    }
  }

  crearIngredienteEnPlato(
    ingrediente: Ingrediente,
    dropPoint?: DropPoint,
    preferDropPoint = false,
    fixedPosition?: { x: number; y: number }
  ): IngredienteEnPlato | null {
    const plateRect = this.getPlateRect();
    if (!plateRect) {
      return null;
    }

    const visualSize = this.getVisualSize(ingrediente);
    const position = fixedPosition
      ? fixedPosition
      : this.obtenerPosicionDisponible(plateRect, visualSize, dropPoint, preferDropPoint);

    if (!position) {
      return null;
    }

    return {
      ingrediente,
      cantidad: ingrediente.porcionDefault,
      unidad: ingrediente.unidad,
      x: position.x,
      y: position.y,
      size: visualSize,
      rotation: this.getRandomRotation()
    };
  }

  eliminarIngrediente(index: number): void {
    this.ingredienteEliminado.emit(index);
  }

  onLimpiarPlato(): void {
    this.limpiarSolicitado.emit();
  }

  get cantidadTotal(): number {
    return this.ingredientesEnPlato.reduce((total, item) => {
      if (item.unidad === 'gramos') {
        return total + item.cantidad;
      }

      if (item.unidad === 'unidad' || item.unidad === 'unidades') {
        const pesosPorUnidad: { [key: string]: number } = {
          'Huevo': 50,
          'Naranja': 150,
          'Cambur': 120
        };
        const pesoPorUnidad = pesosPorUnidad[item.ingrediente.nombre] || 100;
        return total + (item.cantidad * pesoPorUnidad);
      }

      if (item.unidad === 'rebanadas') {
        const pesosPorRebanada: { [key: string]: number } = {
          'Pan': 30,
          'Tomate': 25,
          'Lechosa': 80,
          'Piña': 60
        };
        const pesoPorRebanada = pesosPorRebanada[item.ingrediente.nombre] || 30;
        return total + (item.cantidad * pesoPorRebanada);
      }

      return total;
    }, 0);
  }

  servirPlato(): void {
    if (!this.ingredientesEnPlato.length) {
      return;
    }

    const componentesServidos: ComponenteServido[] = this.ingredientesEnPlato.map(item => {
      let cantidadEnGramos = item.cantidad;

      if (item.unidad !== 'gramos') {
        if (item.unidad === 'unidad' || item.unidad === 'unidades') {
          const pesosPorUnidad: { [key: string]: number } = {
            'Huevo': 50,
            'Naranja': 150,
            'Cambur': 120
          };
          cantidadEnGramos = item.cantidad * (pesosPorUnidad[item.ingrediente.nombre] || 100);
        } else if (item.unidad === 'rebanadas') {
          const pesosPorRebanada: { [key: string]: number } = {
            'Pan': 30,
            'Tomate': 25,
            'Lechosa': 80,
            'Piña': 60
          };
          cantidadEnGramos = item.cantidad * (pesosPorRebanada[item.ingrediente.nombre] || 30);
        }
      }

      return {
        componente_id: item.ingrediente.id,
        nombre: item.ingrediente.nombre,
        cantidad_gramos: cantidadEnGramos,
        imagen: item.ingrediente.imagen
      };
    });

    this.platoServido.emit(componentesServidos);
  }

  getImagePath(imagen: string): string {
    return `assets/images/ingredientes/${imagen}`;
  }

  private getPlateRect(): DOMRect | null {
    const element = this.plateImageRef?.nativeElement || this.plateAreaRef?.nativeElement;
    return element?.getBoundingClientRect() || null;
  }

  private obtenerPosicionDisponible(
    plateRect: DOMRect,
    size: number,
    dropPoint?: DropPoint,
    preferDropPoint = false
  ): { x: number; y: number } | null {
    const radius = Math.min(plateRect.width, plateRect.height) / 2 * 0.85;

    const preferred = dropPoint ? this.convertToPercentage(dropPoint, plateRect, radius, size) : null;
    if (preferred) {
      return preferred;
    }

    if (dropPoint && preferDropPoint) {
      return null;
    }

    // Intento en espiral
    const centerX = plateRect.width / 2;
    const centerY = plateRect.height / 2;
    const angleStep = Math.PI / 12;
    const radiusStep = 20;
    const maxRadius = radius - size / 2;

    for (let r = 20; r <= maxRadius; r += radiusStep) {
      for (let angle = 0; angle < 2 * Math.PI; angle += angleStep) {
        const x = centerX + r * Math.cos(angle);
        const y = centerY + r * Math.sin(angle);
        const percent = this.validateAndConvertPosition(x, y, plateRect, radius, size);
        if (percent) {
          return percent;
        }
      }
    }

    // Intentos aleatorios
    for (let i = 0; i < 150; i++) {
      const angle = Math.random() * 2 * Math.PI;
      const randomRadius = Math.random() * (radius - size / 2);
      const x = (plateRect.width / 2) + randomRadius * Math.cos(angle);
      const y = (plateRect.height / 2) + randomRadius * Math.sin(angle);
      const percent = this.validateAndConvertPosition(x, y, plateRect, radius, size);
      if (percent) {
        return percent;
      }
    }

    return null;
  }

  private calcularPosicionManual(
    pointer: { x: number; y: number } | null,
    ingrediente: Ingrediente
  ): { x: number; y: number } | null {
    if (!pointer) {
      return null;
    }

    const plateRect = this.getPlateRect();
    if (!plateRect) {
      return null;
    }

    const dropX = pointer.x - plateRect.left;
    const dropY = pointer.y - plateRect.top;

    // Para drops manuales, aceptar cualquier posición dentro del área del plato
    // sin validar radio circular ni solapamiento
    if (dropX >= 0 && dropX <= plateRect.width && dropY >= 0 && dropY <= plateRect.height) {
      return {
        x: (dropX / plateRect.width) * 100,
        y: (dropY / plateRect.height) * 100
      };
    }

    return null;
  }

  private convertToPercentage(dropPoint: DropPoint, plateRect: DOMRect, radius: number, size: number) {
    const xRelative = dropPoint.x - plateRect.left;
    const yRelative = dropPoint.y - plateRect.top;
    return this.validateAndConvertPosition(xRelative, yRelative, plateRect, radius, size);
  }

  private validateAndConvertPosition(
    x: number,
    y: number,
    plateRect: DOMRect,
    radius: number,
    size: number,
    enforceSeparation = false
  ) {
    const centerX = plateRect.width / 2;
    const centerY = plateRect.height / 2;
    const distanceFromCenter = Math.sqrt(Math.pow(x - centerX, 2) + Math.pow(y - centerY, 2));

    // Solo validar que esté dentro del radio del plato
    if (distanceFromCenter + size / 2 > radius) {
      return null;
    }

    // Para drops manuales (drag & drop), no validar solapamiento para mayor fluidez
    // Solo validar solapamiento si se solicita explícitamente (para posiciones automáticas)
    if (enforceSeparation && this.seSuperponeConExistentes(x, y, plateRect, size)) {
      return null;
    }

    return {
      x: (x / plateRect.width) * 100,
      y: (y / plateRect.height) * 100
    };
  }

  private seSuperponeConExistentes(x: number, y: number, plateRect: DOMRect, newSize: number): boolean {
    // Permitir hasta 40% de solapamiento para hacer más fácil colocar comida
    const maxOverlap = 0.4;
    return this.ingredientesEnPlato.some(item => {
      const existingX = (item.x / 100) * plateRect.width;
      const existingY = (item.y / 100) * plateRect.height;
      const distance = Math.hypot(x - existingX, y - existingY);
      const minDistance = (newSize / 2) + (item.size / 2) - (Math.min(newSize, item.size) * maxOverlap);
      return distance < minDistance;
    });
  }

  private getRandomRotation(): number {
    return Math.floor(Math.random() * 30) - 15;
  }

  private getVisualSize(ingrediente: Ingrediente): number {
    const base = this.tamanosVisuales[ingrediente.nombre] ?? 45;
    return Math.round(base * 2.5);
  }
}

<div class="scene-wrapper">
  <div class="scene-container">
    <div class="table-scene">
      <div class="table-container">
        <div class="table-with-mantel">
          <img [src]="personajeImagen" alt="Personaje"
               class="personaje-image"
               [class.personaje-image--matias]="personajeActual?.nombre === 'Matias'"
               [class.personaje-image--pedro]="personajeActual?.nombre === 'Pedro'"
               *ngIf="personajeImagen">
          <img [src]="mesaImagen" alt="Mesa" class="mesa-image">
          <img [src]="mantelImagen" alt="Mantel" class="mantel-image">

          <div class="plate-container" id="plate-container" [class.drag-over]="isDragOver">
            <img #plateImage [src]="platoImagen" alt="Plato" class="plate-image">
            <div #plateArea
                 class="plate-area"
                 data-plato-drop-area
                 role="presentation">
            </div>

            <div class="food-on-plate"
                 *ngFor="let item of ingredientesEnPlato; let i = index; trackBy: trackByIndex"
                 [ngStyle]="{
                   'left.%': item.x,
                   'top.%': item.y,
                   'width.px': item.size,
                   'height.px': item.size,
                   'transform': 'translate(-50%, -50%) rotate(' + item.rotation + 'deg)'
                 }"
                 (click)="eliminarIngrediente(i)"
                 title="Eliminar {{ item.ingrediente.nombre }}">
              <img [src]="getImagePath(item.ingrediente.imagen)"
                   [alt]="item.ingrediente.nombre"
                   [attr.data-imagen]="item.ingrediente.imagen">
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="button-container">
    <div class="cantidad-total font-text">
      <span class="label">Total aproximado:</span>
      <span class="value">{{ cantidadTotal | number:'1.0-0' }} g</span>
    </div>
    <button class="btn clear-plate-btn font-text" type="button" (click)="onLimpiarPlato()">
      Limpiar Plato
    </button>
    <button class="btn btn-primary font-text"
            type="button"
            (click)="servirPlato()"
            [disabled]="ingredientesEnPlato.length === 0">
      Finalizar Plato
    </button>
  </div>
</div>

// react-app/src/components/PlatoDropZone.tsx
import { useMemo, useRef, useState } from "react";
import type { ComponenteServido, Ingrediente, IngredienteEnPlato, PersonajeSintetico } from "../types/game";
import { personajeImagenSrc } from "../utils/personajeAssets";

interface Props {
  personajeActual: PersonajeSintetico | null;
  ingredientesEnPlato: IngredienteEnPlato[];
  onIngredienteAgregado: (ingrediente: IngredienteEnPlato) => void;
  onIngredienteEliminado: (index: number) => void;
  onLimpiarPlato: () => void;
  onServirPlato: (componentes: ComponenteServido[]) => void;
  getDraggedIngredient: () => Ingrediente | null;
  getIngredienteById: (id: number) => Ingrediente | undefined;
  clearDraggedIngredient: () => void;
}

const tamanosVisuales: Record<string, number> = {
  Pollo: 50, Bistecs: 55, Huevo: 45, Tocineta: 45, Arroz: 45, "Plátano": 48, Papa: 45, Pasta: 48, Granos: 45,
  Pan: 50, Tomate: 38, Lechuga: 42, "Brócoli": 45, Zanahoria: 48, Pepino: 40, Naranja: 45, Lechosa: 50, Cambur: 45, Fresa: 40, "Piña": 55,
};

export function PlatoDropZone({
  personajeActual,
  ingredientesEnPlato,
  onIngredienteAgregado,
  onIngredienteEliminado,
  onLimpiarPlato,
  onServirPlato,
  getDraggedIngredient,
  getIngredienteById,
  clearDraggedIngredient,
}: Props) {
  const plateImageRef = useRef<HTMLImageElement | null>(null);
  const [isDragOver, setIsDragOver] = useState(false);

  const personajeImagen = useMemo(() => personajeImagenSrc(personajeActual?.imagen), [personajeActual?.imagen]);

  const getPlateRect = () => plateImageRef.current?.getBoundingClientRect() ?? null;

  const validateAndConvert = (x: number, y: number, plateRect: DOMRect, size: number) => {
    const centerX = plateRect.width / 2;
    const centerY = plateRect.height / 2;
    const radius = Math.min(plateRect.width, plateRect.height) / 2 * 0.85;
    const distance = Math.hypot(x - centerX, y - centerY);
    if (distance + size / 2 > radius) return null;
    return { x: (x / plateRect.width) * 100, y: (y / plateRect.height) * 100 };
  };

  const crearIngredienteEnPlato = (ingrediente: Ingrediente, pointer?: { x: number; y: number }): IngredienteEnPlato | null => {
    const plateRect = getPlateRect();
    if (!plateRect) return null;
    const size = Math.round((tamanosVisuales[ingrediente.nombre] ?? 45) * 2.5);
    let pos: { x: number; y: number } | null = null;

    if (pointer) {
      pos = validateAndConvert(pointer.x - plateRect.left, pointer.y - plateRect.top, plateRect, size);
    }
    if (!pos) {
      for (let i = 0; i < 120; i++) {
        const angle = Math.random() * 2 * Math.PI;
        const radius = Math.random() * (Math.min(plateRect.width, plateRect.height) / 2 - size / 2 - 10);
        const x = plateRect.width / 2 + radius * Math.cos(angle);
        const y = plateRect.height / 2 + radius * Math.sin(angle);
        pos = validateAndConvert(x, y, plateRect, size);
        if (pos) break;
      }
    }
    if (!pos) return null;

    return {
      ingrediente,
      cantidad: ingrediente.porcionDefault,
      unidad: ingrediente.unidad,
      x: pos.x,
      y: pos.y,
      size,
      rotation: Math.floor(Math.random() * 30) - 15,
    };
  };

  const handleDrop = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    setIsDragOver(false);
    const ingredienteIdRaw =
      event.dataTransfer.getData("application/x-ingrediente-id") || event.dataTransfer.getData("text/plain");
    const ingredienteId = Number(ingredienteIdRaw);
    const ingredienteFromDataTransfer = Number.isFinite(ingredienteId) ? getIngredienteById(ingredienteId) : undefined;
    const ingrediente = ingredienteFromDataTransfer ?? getDraggedIngredient();
    if (!ingrediente) return;
    const nuevo = crearIngredienteEnPlato(ingrediente, { x: event.clientX, y: event.clientY });
    if (nuevo) onIngredienteAgregado(nuevo);
    clearDraggedIngredient();
  };

  const cantidadTotal = ingredientesEnPlato.reduce((total, item) => {
    if (item.unidad === "gramos") return total + item.cantidad;
    if (item.unidad === "unidad" || item.unidad === "unidades") {
      const pesos: Record<string, number> = { Huevo: 50, Naranja: 150, Cambur: 120 };
      return total + item.cantidad * (pesos[item.ingrediente.nombre] ?? 100);
    }
    if (item.unidad === "rebanadas") {
      const pesos: Record<string, number> = { Pan: 30, Tomate: 25, Lechosa: 80, "Piña": 60 };
      return total + item.cantidad * (pesos[item.ingrediente.nombre] ?? 30);
    }
    return total;
  }, 0);

  const servirPlato = () => {
    if (!ingredientesEnPlato.length) return;
    const componentes = ingredientesEnPlato.map((item) => {
      let cantidad = item.cantidad;
      if (item.unidad === "unidad" || item.unidad === "unidades") {
        const pesos: Record<string, number> = { Huevo: 50, Naranja: 150, Cambur: 120 };
        cantidad = item.cantidad * (pesos[item.ingrediente.nombre] ?? 100);
      } else if (item.unidad === "rebanadas") {
        const pesos: Record<string, number> = { Pan: 30, Tomate: 25, Lechosa: 80, "Piña": 60 };
        cantidad = item.cantidad * (pesos[item.ingrediente.nombre] ?? 30);
      }
      return {
        componente_id: item.ingrediente.id,
        nombre: item.ingrediente.nombre,
        cantidad_gramos: cantidad,
        imagen: item.ingrediente.imagen,
      };
    });
    onServirPlato(componentes);
  };

  return (
    <div className="scene-wrapper">
      <div className="scene-container">
        <div className="table-scene">
          <div className="table-container">
            <div className="table-with-mantel">
              {personajeImagen && <img src={personajeImagen} alt="Personaje" className="personaje-image" />}
              <img src="/assets/images/ingredientes/mesa.png" alt="Mesa" className="mesa-image" />
              <img src="/assets/images/ingredientes/mantel.png" alt="Mantel" className="mantel-image" />
              <div className={`plate-container ${isDragOver ? "drag-over" : ""}`}>
                <img ref={plateImageRef} src="/assets/images/ingredientes/plato.png" alt="Plato" className="plate-image" />
                <div
                  className="plate-area"
                  onDrop={handleDrop}
                  onDragOver={(e) => {
                    e.preventDefault();
                    e.dataTransfer.dropEffect = "copy";
                    setIsDragOver(true);
                  }}
                  onDragEnter={(e) => {
                    e.preventDefault();
                    setIsDragOver(true);
                  }}
                  onDragLeave={(e) => {
                    e.preventDefault();
                    setIsDragOver(false);
                  }}
                />
                {ingredientesEnPlato.map((item, i) => (
                  <div
                    key={`${item.ingrediente.id}-${i}`}
                    className="food-on-plate"
                    style={{
                      left: `${item.x}%`,
                      top: `${item.y}%`,
                      width: `${item.size}px`,
                      height: `${item.size}px`,
                      transform: `translate(-50%, -50%) rotate(${item.rotation}deg)`,
                    }}
                    onClick={() => onIngredienteEliminado(i)}
                    title={`Eliminar ${item.ingrediente.nombre}`}
                  >
                    <img src={`/assets/images/ingredientes/${item.ingrediente.imagen}`} alt={item.ingrediente.nombre} data-imagen={item.ingrediente.imagen} />
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="button-container">
        <div className="cantidad-total font-text">
          <span className="label">Total aproximado:</span>
          <span className="value">{Math.round(cantidadTotal)} g</span>
        </div>
        <button className="btn clear-plate-btn font-text" type="button" onClick={onLimpiarPlato}>
          Limpiar Plato
        </button>
        <button className="btn btn-primary font-text" type="button" onClick={servirPlato} disabled={!ingredientesEnPlato.length}>
          Finalizar Plato
        </button>
      </div>
    </div>
  );
}
